### ISSUE TITLE
Update PhpUnit version (dependency + tests)

### ISSUE THREAD

**Issue by toubsen** [bzikarsky/gelf-php#107]
Tests for this library rely on PhpUnit 4.x (via composer.json) at max 5.x (usage of getMock()). It'd make sense in the long run (e.g. 2.x) to update + refactor to a newer supported PhpUnit version (>= 7) as a dependency.

**Comment by Tobion** [comment]
Looks like it uses phpunit 7 in 2.0 now. I could be upped to phpunit 8 with its current php: ^7.2 requirement.

**Comment by bzikarsky** [comment]
Agree, as mentioned previously...2.0 development is kinda in a void currently. I will probably revisit a lot of the decisions (min php version, phpunit version, etc.) once I am coming back to this.

**Comment by bzikarsky** [comment]
I updated master (and therefore 1.x) to make use of phpunit 5, 6 or 7 and droped PHP support for anything older than 5.6 with that. I don't have time to do any reasonable development on 2.x and this at least allows future maintenance work on 1.x
