### ISSUE TITLE
v1.6 should require paragonie/constant_time_encoding ^1|^2 instead of just ^1

### ISSUE THREAD

**Issue by jhammer** [bzikarsky/gelf-php#114]
The [PHP version requirements](https://github.com/paragonie/constant_time_encoding) for paragonie/constant_time_encoding give the following guidance:

> If you are adding this as a dependency to a project intended to work on both PHP 5 and PHP 7, please set the required version to ^1|^2 instead of just ^1 or ^2.

Currently gelf-php is requiring constant_time_encoding ^1. This is blocking us from using other paragonie packages that require ^2 when running under PHP 7.x.

The release notes for gelf-php 1.6.0 highlight PHP 7.1 compatibility. As such, it would be really great if a v1.6.1 release could be cut that uses the recommended constant_time_encoding ^1|^2. That would unblock us and make 1.6.1 truly PHP 7.x compatible.

Thanks for considering!

**Comment by bzikarsky** [comment]
Thanks, I'll tag when the tests pass.

**Comment by jhammer** [comment]
Awesome, thank you!

**Comment by jhammer** [comment]
Thank you!
