### ISSUE TITLE
fix preg_match in HttpTransport

### ISSUE THREAD

**Issue by lemon777** [bzikarsky/gelf-php#116]
https://github.com/bzikarsky/gelf-php/blob/2344540be1db5e882990d527588649e065efbde0/src/Gelf/Transport/HttpTransport.php#L222
https://github.com/bzikarsky/gelf-php/blob/2344540be1db5e882990d527588649e065efbde0/src/Gelf/Transport/HttpTransport.php#L226

Replace exclamation marks with slash in preg_match

**Comment by bzikarsky** [comment]
Can you create a PR? That would be easier to read/manage. Thanks :-)
