### ISSUE TITLE
problem with sending data to logstash error code :111

### ISSUE THREAD

**Issue by farshadff** [bzikarsky/gelf-php#120]
i have configured my laravel project as a toturial i link it below :
```
https://matthewdaly.co.uk/blog/2018/06/03/logging-to-the-elk-stack-with-laravel/
```
but when i want to send data to my elastic search i get this error in my tinker :  
```
//this is my tinker console that logs the data >>> Log::info('Just testing');
RuntimeException with message 'Failed to write to socket: fwrite(): send of 131 bytes failed with errno=111 Connection refused (8)'
```

**Comment by bzikarsky** [comment]
Have you checked that your port is open and not firewalled off? The error-message pretty much tells you directly to your face that it cannot connect to the configured host at the given port via TCP. Use tcping, nmap or something similiar to debug your network issues.

This is *very likely* not gelf-php related.
