### ISSUE TITLE
Passing the glue after the pieces has been deprecated. 

### ISSUE THREAD

**Issue by cwuensche** [bzikarsky/gelf-php#122]
https://github.com/bzikarsky/gelf-php/blob/23926624813482f6ef0d48d777ac0c1611d22e6b/src/Gelf/Transport/HttpTransport.php#L215

**Comment by bzikarsky** [comment]
That's true. Thanks for bringing this up, fixed this directly in master https://github.com/bzikarsky/gelf-php/commit/4502a39fc602d4037ae954bc9b1fa63acb10c3e1

Will probably also tag a hotfix release in a few minutes.
