### ISSUE TITLE
PHP Parse error Binary.php on line 46 using the tcp-example.php

### ISSUE THREAD

**Issue by rpelletierrefocus** [bzikarsky/gelf-php#123]
I am getting this error using PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/bangordailynews.com/htdocs/wp-content/plugins/bpc-elections-new/includes/gelf-php/paragonie/constant_time_encoding/src/Binary.php on line 46

**Comment by rpelletierrefocus** [comment]
My php version is 
PHP 5.6.31  and there is no possibility of upgrading it. Will the 1.x branch of paragonie work with this?

**Comment by rpelletierrefocus** [comment]
Tried it and the answer is yes, the 1.x branch works fine.

**Comment by bzikarsky** [comment]
You could probably force paragonie/constant_time_encoding to a 1.x version in your composer.json and it work with a stable version of gelf-php as well. Haven tried this though.
