### ISSUE TITLE
The current Keep-Alive implementation in HttpTransport is incomplete

### ISSUE THREAD

**Issue by xel1045** [bzikarsky/gelf-php#127]
When using gelf-php in TCP for long running processes (in our case Laravel's queue system), we see a lot of these errors:

```
Graylog-Server didn't answer properly, expected 'HTTP/1.x 202 Accepted', response is ''
```

After digging into the code, I see that a `Keep-Alive` connection is established, but when the server close the socket, the next logged message will throw the exception above. Thus, the message that is attempting to be logged will be lost.

When initializing a `Keep-Alive` connection, it could be closed by the server after a certain timeout or a number of requests (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive).

To fix this, I see two possible approaches:

1. Stop initializing a `Keep-Alive` connection by passing `Connection: Close`;
2. Add a retry mechanism when a connection is closed (see https://tools.ietf.org/html/rfc7230#section-6.3.1).

**Comment by pgrenaud** [comment]
Hi! Colleague of @xel1045 here.

We are open to send a PR, but we would first like to know which method would you prefer. There is also a third option possible which would be doing both and adding an option to enable/disable keep-alive connections.

Let us know if you have any questions or if you need any additional details. In the mean time, we have forked the repo and applied a temporary fix, be we would rather fix the issue upstream! 🙂

**Comment by bzikarsky** [comment]
Sorry for being a bit unresponsive, there is a lot of going on these days. 

Your first option seems doable via a easy flag on the transport but feels terrible from a performance standpoint.

Second option might be preferable if it's only happening once in a while. I'd probably implement it as a decorator in this case, similar to the error suppressing transport.

**Comment by xel1045** [comment]
On our side too, we are quite busy, but we'll try to look into it soon and submit a PR with a decorator as you suggested.

Thanks for your input!
