### ISSUE TITLE
gelf library under psr v3

### ISSUE THREAD

**Issue by kvelaro** [bzikarsky/gelf-php#137]
We could not install gelf-php, because it's not supporting psr v3 yet. 

Are you planning to release this support soon?

**Comment by bzikarsky** [comment]
Can you use https://github.com/bzikarsky/gelf-php/releases/tag/2.0.0-beta.1?

I haven't gotten about potential issues. So I might be able to tag a stable 2.0 soonish. I

**Comment by kvelaro** [comment]
Thank you, tested on beta version. For now it will suffice. Waiting for stable version.
