### ISSUE TITLE
Attempted to call an undefined method named setFacility of class Gelf\Message

### ISSUE THREAD

**Issue by mboron83** [bzikarsky/gelf-php#140]
Hi, this is my environment configuration

**php version: 8.1.13**
**symfony version: 5.4.16**
**graylog2/gelf-php version: 2.0.0**

Symfony\Component\ErrorHandler\Error\UndefinedMethodError^ {#2970
  #message: **"Attempted to call an undefined method named "setFacility" of class "Gelf\Message"."**
  #code: 0
  #file: "./vendor/monolog/monolog/src/Monolog/Formatter/GelfMessageFormatter.php"
  #line: 117
  trace: {
    ./vendor/monolog/monolog/src/Monolog/Formatter/GelfMessageFormatter.php:117 { …}
    ./vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:46 { …}
    ./vendor/monolog/monolog/src/Monolog/Logger.php:379 { …}
    ./vendor/monolog/monolog/src/Monolog/Logger.php:626 { …}
    ./src/Command/GraylogCommand.php:30 {
      App\Command\GraylogCommand->__construct(LoggerInterface $graylogLogger)^
      ›     parent::__construct();
      ›     $this->graylogLogger->error('Lorem');
      › }
      arguments: {
        $message: "Lorem"
      }
    }
    ./var/cache/dev/ContainerXi1iIAb/getGraylogCommandService.php:23 { …}
    ./var/cache/dev/ContainerXi1iIAb/App_KernelDevDebugContainer.php:581 { …}
    ./var/cache/dev/ContainerXi1iIAb/getGraylogCommand_LazyService.php:24 { …}
    ./vendor/symfony/console/Command/LazyCommand.php:201 { …}
    ./vendor/symfony/console/Application.php:297 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:82 { …}
    ./vendor/symfony/console/Application.php:171 { …}
    ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
    ./vendor/autoload_runtime.php:35 { …}
    ./bin/console:11 { …}
  }
}

Previous version (1.7.1) seems to work perfect.

**Comment by bzikarsky** [comment]
What's the monolog version? Monolog got updated with gelf-php v2 support in https://github.com/Seldaek/monolog/commit/5eccd17dc5bad181ac6442100460b136f6b76894. *But this is not tagged in a release yet*. For now there is no supported way to use Symfony/Monolog with gelf-php 2.

**Comment by mboron83** [comment]
> What's the monolog version? Monolog got updated with gelf-php v2 support in [Seldaek/monolog@5eccd17](https://github.com/Seldaek/monolog/commit/5eccd17dc5bad181ac6442100460b136f6b76894). _But this is not tagged in a release yet_. For now there is no supported way to use Symfony/Monolog with gelf-php 2.

I have https://packagist.org/packages/symfony/monolog-bundle#v3.8.0 version
