### ISSUE TITLE
Upgrade 1.7.1 to 2.0.0

### ISSUE THREAD

**Issue by hulkthedev** [bzikarsky/gelf-php#144]
Hello everyone,
I'm in the process of updating and unfortunately I have to realize that "facility" has been thrown out. Unfortunately I can't find a word about it anywhere.

How is the facility allocated?
Thanks

**Comment by r-simlinger** [comment]
https://go2docs.graylog.org/5-0/getting_in_log_data/gelf.html#GELFPayloadSpecification

> optional, deprecated. Send as additional field instead.

```
->setAdditional('facility', '...');
```

**Comment by bzikarsky** [comment]
Thanks for answering. This is on point. :)
