### ISSUE TITLE
Fix message-to-array conversion / better support for multiple GELF standards 

### ISSUE THREAD

**Issue by bzikarsky** [bzikarsky/gelf-php#23]
# Tasklist

- [ ] Move message-to-array logic to classes (separate ones for 1.0 and 1.1) `SerializerInterface` which convert the message to a JsonSerializable structure
- [ ] Move any logic revolving around `$version` or `getVersion` from `Message` to the serializers
- [ ] Move message-validation to serializers 

# Original issue

There is currently a condition in place to handle 1.0 and 1.1 message serialization. (https://github.com/bzikarsky/gelf-php/blob/30bdad76661bad60714734bf24e00b8a82131aa2/src/Gelf/Message.php#L279)

When the GELF 2.0 spec is finalized, we need a better way to support multiple GELF standards.

Achieving this without breaking BC would be optimal. I'd rather not force GELF 2.0 users to a 2.0 upgrade, but if there is no way around so be it.

**Comment by sandrinr** [comment]
I am confused by the code here which references to this issue:
https://github.com/bzikarsky/gelf-php/blob/master/src/Gelf/Message.php#L289

Why is it even needed? That code converts, for messages in GELF version 1.1,  the fields `line`, `facility`, `file` to additional fields. However, according to the GELF doc (http://docs.graylog.org/en/2.0/pages/gelf.html) these are perfectly fine fields with GELF 1.1.

**Comment by bzikarsky** [comment]
While it's still possible to send them as separate fields, the docs also tag them as deprecated. I'd rather not generate any deprecation-warnings on the gelf-backend fed with gelf-php messages.

Is it (the current implementation) causing any problems for you?

**Comment by sandrinr** [comment]
Thank you for your response. The current implementation is not causing problems for me. I just stumbled over this while analyzing the behavior the gelf-php library within a Symfony2 application.

**Comment by bzikarsky** [comment]
I am closing this. There have been no further moves on gelf versions, so I'll just drop all support multiple gelf-versions.
