### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by MaximeBaldin** [bzikarsky/gelf-php#29]
https://github.com/bzikarsky/gelf-php/blob/master/src/Gelf/Publisher.php#L69
$reason is undefined variable

**Comment by bzikarsky** [comment]
Checkout https://github.com/bzikarsky/gelf-php/blob/master/src/Gelf/MessageValidator.php#L24 - it's passed by reference. 

Did you run in any issues with that?

**Comment by bzikarsky** [comment]
Is this issue still relevant @MaximeBaldin? If not, please close the issue (or I will, the next time I come by it :wink:)

**Comment by MaximeBaldin** [comment]
@bzikarsky, from where $reason is taken in the method call?
It is not declared in this method https://github.com/bzikarsky/gelf-php/blob/master/src/Gelf/Publisher.php#L61.
As I got, in this code method $this->messageValidator->validate($message, $reason) always got undefined $reason.

My IDE highlights $this->messageValidator->validate($message, $reason) because of undefined $reason. This is about this issue.

**Comment by bzikarsky** [comment]
Then your IDE is not correct - PHP does not require a passed-by-reference variable to be defined before the function call. 

This behavior is true for all versions of PHP5 and HHVM: http://3v4l.org/KjO8T

**Comment by MaximeBaldin** [comment]
You are right.
Thanks for reply.
