### ISSUE TITLE
Drop PHP5 and HHVM support in 2.0

### ISSUE THREAD

**Issue by bzikarsky** [bzikarsky/gelf-php#35]
Requires analysis: Maybe it's even feasible to drop full 5.x support when 2.0 starts to become reality.

**Comment by tralafiti** [comment]
Right now PHP <5.3.9 isn't working anyway due to a bug related to redeclaration of abstract functions:
```php
PHP Fatal error:  Can't inherit abstract function Gelf\\Transport\\TransportInterface::send() (previously declared abstract in Gelf\\Transport\\AbstractTransport)
```
This bug was fixed in https://github.com/php/php-src/commit/31ef559712dae57046b6377f07634ad57f9d88cf#Zend/zend_compile.c 

Could you please adjust the requirement in composer.json in the mean time?

**Comment by bzikarsky** [comment]
@tralafiti Thanks for the hint - I'll look into this.

**Comment by tralafiti** [comment]
@bzikarsky Great, thank you!

**Comment by bzikarsky** [comment]
Decided to also tag this as 1.2.1 also.

**Comment by misilot** [comment]
@bzikarsky Do you know what the last version to support 5.3.3 would be? 

As we have a library that needs to support 5.3.3 and 5.4,5.6, and 7.0.

Thanks!

**Comment by Tobion** [comment]
Looks like it can be closed considering https://github.com/bzikarsky/gelf-php/issues/110

**Comment by bzikarsky** [comment]
Hm, probably yes. I was a bit quick on the trigger-finger yesterday night and "rolled back".

2.0 development kind of dozed off as the need is currently not big enough. The current version still mostly works good enough.

In answer to the original question (from 2016 ... oops :roll_eyes:): The current 1.x development line will try to keep the current minimum versions. A new major version (with a changed API) may use updated version requirements for new fancy language features.

We can still consider this closed, as this is not really "issue-worthy" right now. Thanks for bringing it to my attention.
