### ISSUE TITLE
Option to set connection_timeout, actual hardcoded in StreamSocketClient

### ISSUE THREAD

**Issue by rubao** [bzikarsky/gelf-php#40]
30 secs is too much

maybe if HttpTransport accept another param $socketTimeout, pass to StreamSocketClient this could be used when initSocket() .. what do you think?

**Comment by bzikarsky** [comment]
First of all: I think you make a valid point. having the connect-timeout hardcoded into `StreamSocketClient` does not make sense. I can't remember how it happened, it's probably a fragment of the initial prototype.

Regarding the implementation:: I don't think another constructor argument in either HttpTransport or StreamSocketClient is a good idea. 

I propose the following changes to ensure backwards compatibility:

`StreamSocketClient`:
- Mark `SOCKET_TIMEOUT` as deprecated
- Mark `protected static initSocket()` as deprecated
- Add `protected $connectTimeout = 30`, `public getConnectTimeout()` and `public setConnectTimeout()`
-

**Comment by rubao** [comment]
hey @bzikarsky thanks, this helps a lot.

just another question: what you thing about `stream_set_timeout()` could be another option?

i dont know if it's just with me, but sometimes Graylog take ages to answer after connect, this could help

**Comment by bzikarsky** [comment]
Hm, this pollutes the StreamSocketClient with more and more tcp specific options, while its UDP functionality is the "standard" way of implementing GELF. It's probably time to split this into two different classes and expose the TCPSocketClient on the TCP using transports, so we do not need to proxy every single TCP specific option.

**Comment by rubao** [comment]
you are right, should I open a new issue?

**Comment by bzikarsky** [comment]
Yes please. But this is not going to be easy without breaking BC. 

Please don't get your hopes up for a quick fix, I'm quite busy the next 1,2 weeks, so it'll take a while.

**Comment by rubao** [comment]
no problem, I did a workaround to set the strem_timeout after getSocket()
