### ISSUE TITLE
Message with boolean value is filtered out

### ISSUE THREAD

**Issue by hrach** [bzikarsky/gelf-php#46]
Currently, if some key has boolean value, is wrongly converted empty string and filtered out as empty value. #38 solves this, but it's somehow stuck and also solves an another problem.

**Comment by bzikarsky** [comment]
Yeah, the filtering (currently `strlen`) needs additional checks: `is_bool` and `is_null` -- It'll be fixed in the next minor release.

**Comment by hrach** [comment]
thanks!
