### ISSUE TITLE
Is CHUNK_MAX_COUNT too big?

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [bzikarsky/gelf-php#48]
> A message MUST NOT consist of more than 128 chunks.
(c) https://www.graylog.org/resources/gelf/

But I [see](https://github.com/bzikarsky/gelf-php/blob/95819a761f4b638249fbd583064757f8579cd76d/src/Gelf/Transport/UdpTransport.php#L30) that your lib allowing up to 256 chunks. Please clarify which is correct.

Also I see logstash logs messages like this:
```ruby
{
  :timestamp=>"2015-10-14T13:38:01.927000+0300",
  :message=>"Gelfd failed to parse a message skipping",
  :exception=>#<Gelfd::TooManyChunksError: 130 greater than 128>,
  :backtrace=>[
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/gelfd-0.2.0/lib/gelfd/chunked_parser.rb:40:in `parse_chunk'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/gelfd-0.2.0/lib/gelfd/chunked_parser.rb:8:in `parse'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/gelfd-0.2.0/lib/gelfd/parser.rb:10:in `parse'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-1.0.0/lib/logstash/inputs/gelf.rb:100:in `udp_listener'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-1.0.0/lib/logstash/inputs/gelf.rb:62:in `run'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:177:in `inputworker'",
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:171:in `start_input'"
  ],
  :level=>:warn
}
```

**Comment by bzikarsky** [comment]
Just checked the docs, 128 is correct. Needs a fix in https://github.com/bzikarsky/gelf-php/blob/master/src/Gelf/Transport/UdpTransport.php#L30
and new tests (for max chunk count) in https://github.com/bzikarsky/gelf-php/blob/master/tests/Gelf/Test/Transport/UdpTransportTest.php.

A PR would be appreciated very much -- I'm now sure when I'll find hthe time for a proper fix.

**Comment by bzikarsky** [comment]
Will be fixed in the next minor release

**Comment by AlexeyKupershtokh** [comment]
I see you didn't add any tests by yourself you requested earlier :) Only this stopped me from creating a PR.
Anyway, thank you!

**Comment by bzikarsky** [comment]
I realized there were already tests in https://github.com/bzikarsky/gelf-php/blob/master/tests/Gelf/Test/Transport/UdpTransportTest.php#L123-L127 when I started to write the tests.
