### ISSUE TITLE
fwrite return values

### ISSUE THREAD

**Issue by cyrip** [bzikarsky/gelf-php#66]
Hello,

I use php 5.6 on debian jessy.
I have a problem with TCPTransport.

I establish a connection to tha graylog2 server.
Everything is fine but when an error occurred, for example "Connection reset by peer" or "Broken pipe" - when I shutdown graylog2 infrastructure
fwrite returns with int(0), not boolean false value so "Failed to write to socket" exception will not be thrown because of $byteCount === false condition

Only the the following notice are generated:
Message: fwrite(): send of 166 bytes failed with errno=104 Connection reset by peer
Message: fwrite(): send of 166 bytes failed with errno=32 Broken pipe

Thx,
Cyr

**Comment by bzikarsky** [comment]
Confirmed. There is a check missing for `bytes-written == message-length` after `fwrite(..)`.
