### ISSUE TITLE
Vardump in check_technical_requirements.php causes Problems

### ISSUE THREAD

**Issue by solutionDrive-Alt** [bzikarsky/gelf-php#75]
Hello,
I just updated to the newest version an got some strange behavior because of this var_dump. Maybe it was forgotten to remove?

Kind regards
Matthias

**Comment by ambroisemaupate** [comment]
It’s there: https://github.com/bzikarsky/gelf-php/blob/master/src/check_technical_requirements.php#L13

**Comment by bzikarsky** [comment]
It's fixed. That was quite dumb. Sorry for the inconvenience.
