### ISSUE TITLE
Provide example configs for Symfony (was: How to configure IgnoreErrorTransportWrapper in config.yml symfony2 project ?)

### ISSUE THREAD

**Issue by karim10** [bzikarsky/gelf-php#86]
I'm trying to stream logs from a symfony 2 app to a graylog 2 server using the gelf format.
My monolog configuration looks as follows:
` monolog:
    handlers:
          graylog:
              type: gelf
              publisher:
                  hostname: my-graylog-server.com
                  port: 12201
              level: debug
              formatter: app.gelf_formatter `
I'm getting a connection refused error when the graylog server is not available. 
`[2017-07-28 16:03:25] app.ERROR: Failed to write to socket: fwrite(): send of 153 bytes failed with errno=111 Connection refused (8) [] []`
This is why I'm looking for how to set IgnoreErrorTransportWrapper option in my config.yml
Any help would be greatly appreciated!

**Comment by gbourgeat** [comment]
I'm interested too !

**Comment by bzikarsky** [comment]
Instead of giving a `type` to a `monolog.handler` you can pass in a service by configuring `id`. This allows you to configure any class (like IgnoreErrorTransportWrapper) as a service and pass it to monolog.

**Comment by mfeltscher** [comment]
I had the exact same issue. After digging more into this I found this pull request for the Monolog Bundle which adds a `ignore_error` option: https://github.com/symfony/monolog-bundle/pull/246
