### ISSUE TITLE
Issues with setAdditional

### ISSUE THREAD

**Issue by kkawatra09** [bzikarsky/gelf-php#98]
Hello,

Is anyone having issues with $message->setAdditional($key,$value) function. Here is the test script

```
<?php
require_once __DIR__ . '/vendor/gelf-php/gelf-php-master/vendor/autoload.php';
$transport = new Gelf\Transport\TcpTransport("<IP>, <PORT>);
$publisher = new Gelf\Publisher();
$publisher->addTransport($transport);
$message = new Gelf\Message();
$message->setShortMessage("It works in TCP!")
        ->setLevel(\Psr\Log\LogLevel::ALERT)
        ->setFullMessage("There was a foo in bar")
        ->setFacility("local8")
;
$message->setAdditional("IP", "10.4.13.45");
//var_dump($message);
$publisher->publish($message);
var_dump($publisher);

```

it works without setAdditional. And I do not see an error with setAdditional part of the script but nothing gets pushed to the graylog server.

**Comment by bzikarsky** [comment]
This doesn't make sense, really. And this functionality is quite well tested. Can you debug this a littlebit further?

**Comment by bzikarsky** [comment]
I'll close this, please reopen if you have more information.
